import { 
  Phone, 
  PhoneOff, 
  Mic, 
  MicOff, 
  Camera, 
  CameraOff,
  MessageSquare,
  User,
  Users,
  Bell,
  Settings,
  Mail,
  Send,
  Plus,
  Check,
  X,
  Search,
  ChevronLeft,
  ChevronRight,
  Menu,
  LogOut,
  Paperclip,
  Image,
  File,
  Smile,
  Monitor,
  MonitorOff
} from 'lucide-react';

export const Icons = {
  phone: Phone,
  phoneOff: PhoneOff,
  mic: Mic,
  micOff: MicOff,
  camera: Camera,
  cameraOff: CameraOff,
  message: MessageSquare,
  user: User,
  users: Users,
  bell: Bell,
  settings: Settings,
  mail: Mail,
  send: Send,
  plus: Plus,
  check: Check,
  x: X,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  logout: LogOut,
  paperclip: Paperclip,
  image: Image,
  file: File,
  smile: Smile,
  monitor: Monitor,
  monitorOff: MonitorOff
}; 