# Configuração do projeto Supabase para o módulo de matrículas
project_id = "npiyusbnaaibibcucspv"

[api]
enabled = true
port = 54321
schemas = ["public", "pagamentos", "auth"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "https://npiyusbnaaibibcucspv.supabase.co"

[functions]
[functions.lytex-webhook]
verify_jwt = false 