import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useBlogAuthorById, useBlogCategories } from '../hooks/useBlog';
export function BlogPostCard({ post, variant = 'default' }) {
    const { data: author } = useBlogAuthorById(post.author_id);
    const { data: allCategories } = useBlogCategories();
    // Encontrar categorias do post
    const postCategories = allCategories?.filter(cat => post.category_ids.includes(cat.id)) || [];
    // Formatar data
    const formattedDate = new Date(post.published_at || post.created_at).toLocaleDateString('pt-BR', {
        day: '2-digit',
        month: 'long',
        year: 'numeric'
    });
    // Verificar se é featured (layout diferente)
    if (variant === 'featured') {
        return (_jsx("div", { className: "bg-white rounded-xl shadow-md overflow-hidden mb-8", children: _jsxs("div", { className: "md:flex", children: [_jsx("div", { className: "md:flex-shrink-0 md:w-1/2", children: post.featured_image_url ? (_jsx("img", { className: "h-full w-full object-cover md:h-full md:w-full", src: post.featured_image_url, alt: post.title })) : (_jsx("div", { className: "h-full w-full bg-primary-100 flex items-center justify-center text-primary-500", children: _jsx("svg", { className: "h-16 w-16", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M4 5a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V7a2 2 0 00-2-2h-1.586a1 1 0 01-.707-.293l-1.121-1.121A2 2 0 0011.172 3H8.828a2 2 0 00-1.414.586L6.293 4.707A1 1 0 015.586 5H4z", clipRule: "evenodd" }) }) })) }), _jsxs("div", { className: "p-8 md:w-1/2", children: [_jsx("div", { className: "flex flex-wrap gap-2 mb-3", children: postCategories.map(category => (_jsx(Link, { to: `/blog/categoria/${category.slug}`, className: "text-xs bg-primary-50 text-primary-700 px-3 py-1 rounded-full", children: category.name }, category.id))) }), _jsx(Link, { to: `/blog/${post.slug}`, className: "block mt-1", children: _jsx("h2", { className: "text-2xl font-bold text-primary-900 hover:text-primary-700 transition", children: post.title }) }), _jsx("p", { className: "mt-3 text-gray-600", children: post.excerpt || post.meta_description || '' }), _jsxs("div", { className: "mt-6 flex items-center", children: [author?.avatar_url ? (_jsx("img", { className: "h-10 w-10 rounded-full mr-3", src: author.avatar_url, alt: author.name })) : (_jsx("div", { className: "h-10 w-10 rounded-full bg-primary-100 flex items-center justify-center mr-3", children: _jsx("span", { className: "text-primary-700 font-medium", children: author?.name.charAt(0) || '?' }) })), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: author?.name }), _jsx("div", { className: "flex space-x-1 text-sm text-gray-500", children: _jsx("time", { dateTime: post.published_at || post.created_at, children: formattedDate }) })] })] })] })] }) }));
    }
    // Variant compact (para sidebar, relacionados, etc)
    if (variant === 'compact') {
        return (_jsxs("div", { className: "flex items-start space-x-3 mb-4", children: [post.featured_image_url && (_jsx("img", { src: post.featured_image_url, alt: post.title, className: "w-16 h-16 object-cover rounded flex-shrink-0" })), _jsxs("div", { children: [_jsx(Link, { to: `/blog/${post.slug}`, className: "text-sm font-medium text-gray-900 hover:text-primary-700 transition line-clamp-2", children: post.title }), _jsx("div", { className: "text-xs text-gray-500 mt-1", children: formattedDate })] })] }));
    }
    // Default card
    return (_jsxs("div", { className: "bg-white rounded-lg shadow-sm overflow-hidden border border-gray-100 h-full transition-shadow hover:shadow-md", children: [post.featured_image_url && (_jsx(Link, { to: `/blog/${post.slug}`, className: "block overflow-hidden", children: _jsx("img", { src: post.featured_image_url, alt: post.title, className: "h-48 w-full object-cover transition-transform hover:scale-105 duration-300" }) })), _jsxs("div", { className: "p-5", children: [postCategories.length > 0 && (_jsxs("div", { className: "flex flex-wrap gap-2 mb-3", children: [postCategories.slice(0, 2).map(category => (_jsx(Link, { to: `/blog/categoria/${category.slug}`, className: "text-xs bg-primary-50 text-primary-700 px-2 py-0.5 rounded-full", children: category.name }, category.id))), postCategories.length > 2 && (_jsxs("span", { className: "text-xs text-gray-500", children: ["+", postCategories.length - 2] }))] })), _jsx(Link, { to: `/blog/${post.slug}`, className: "block", children: _jsx("h3", { className: "text-lg font-semibold text-gray-900 hover:text-primary-700 transition mb-2 line-clamp-2", children: post.title }) }), post.excerpt && (_jsx("p", { className: "text-gray-600 text-sm mb-4 line-clamp-3", children: post.excerpt })), _jsxs("div", { className: "flex items-center justify-between mt-4 pt-4 border-t border-gray-100", children: [_jsxs("div", { className: "flex items-center", children: [author?.avatar_url ? (_jsx("img", { className: "h-6 w-6 rounded-full mr-2", src: author.avatar_url, alt: author.name })) : (_jsx("div", { className: "h-6 w-6 rounded-full bg-primary-100 flex items-center justify-center mr-2", children: _jsx("span", { className: "text-xs text-primary-700 font-medium", children: author?.name.charAt(0) || '?' }) })), _jsx("span", { className: "text-xs text-gray-700", children: author?.name })] }), _jsx("div", { className: "text-xs text-gray-500", children: formattedDate })] })] })] }));
}
export default BlogPostCard;
