export * from './matriculaService'
export * from './cursoService'
export * from './planoService'
export * from './pagamentoService'
export * from './documentoService'
export * from './alunoService'
export * from './contratoService'
export * from './configuracoesService'
export * from './lytexService'
export { default as dashboardService } from './dashboardService' 