import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const Dashboard = () => {
    // Dados de exemplo para os indicadores
    const stats = [
        { name: 'Instituições Parceiras', value: '12', change: '+20%', changeType: 'increase' },
        { name: 'Cursos Ativos', value: '38', change: '+12%', changeType: 'increase' },
        { name: 'Certificações Emitidas', value: '854', change: '+32%', changeType: 'increase' },
        { name: 'Receita Mensal', value: 'R$ 28.475,00', change: '+18%', changeType: 'increase' },
    ];
    // Dados de exemplo para os gráficos
    const recentActivities = [
        { id: 1, activity: 'Faculdade XYZ adicionou novo curso', time: '2 horas atrás', status: 'Em revisão' },
        { id: 2, activity: 'Certificado emitido para João Silva', time: '4 horas atrás', status: 'Concluído' },
        { id: 3, activity: 'Instituto ABC tornou-se parceiro', time: '1 dia atrás', status: 'Ativo' },
        { id: 4, activity: 'Universidade 123 atualizou material', time: '2 dias atrás', status: 'Concluído' },
    ];
    return (_jsxs("div", { children: [_jsxs("div", { className: "pb-5 border-b border-gray-200", children: [_jsx("h2", { className: "text-lg leading-6 font-medium text-gray-900", children: "Dashboard" }), _jsx("p", { className: "mt-2 max-w-4xl text-sm text-gray-500", children: "Vis\u00E3o geral do Portal do Parceiro, com indicadores e atividades recentes." })] }), _jsx("div", { className: "mt-6", children: _jsx("dl", { className: "grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4", children: stats.map((stat) => (_jsxs("div", { className: "relative bg-white pt-5 px-4 pb-6 sm:pt-6 sm:px-6 shadow rounded-lg overflow-hidden", children: [_jsx("dt", { children: _jsx("p", { className: "text-sm font-medium text-gray-500 truncate", children: stat.name }) }), _jsxs("dd", { className: "mt-1 flex justify-between items-baseline md:block lg:flex", children: [_jsx("div", { className: "flex items-baseline text-2xl font-semibold text-indigo-600", children: stat.value }), _jsxs("div", { className: `${stat.changeType === 'increase'
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-red-100 text-red-800'} inline-flex items-baseline px-2.5 py-0.5 rounded-full text-sm font-medium md:mt-2 lg:mt-0`, children: [stat.changeType === 'increase' ? (_jsx("svg", { className: "-ml-1 mr-0.5 flex-shrink-0 self-center h-5 w-5 text-green-500", fill: "currentColor", viewBox: "0 0 20 20", "aria-hidden": "true", children: _jsx("path", { fillRule: "evenodd", d: "M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z", clipRule: "evenodd" }) })) : (_jsx("svg", { className: "-ml-1 mr-0.5 flex-shrink-0 self-center h-5 w-5 text-red-500", fill: "currentColor", viewBox: "0 0 20 20", "aria-hidden": "true", children: _jsx("path", { fillRule: "evenodd", d: "M14.707 10.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 12.586V5a1 1 0 012 0v7.586l2.293-2.293a1 1 0 011.414 0z", clipRule: "evenodd" }) })), _jsxs("span", { className: "sr-only", children: [stat.changeType === 'increase' ? 'Increased' : 'Decreased', " by"] }), stat.change] })] })] }, stat.name))) }) }), _jsxs("div", { className: "mt-8", children: [_jsx("h3", { className: "text-lg leading-6 font-medium text-gray-900", children: "Atividades Recentes" }), _jsx("div", { className: "mt-2 flex flex-col", children: _jsx("div", { className: "-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8", children: _jsx("div", { className: "py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8", children: _jsx("div", { className: "shadow overflow-hidden border-b border-gray-200 sm:rounded-lg", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Atividade" }), _jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Quando" }), _jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Status" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: recentActivities.map((activity) => (_jsxs("tr", { children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-900", children: activity.activity }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500", children: activity.time }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx("span", { className: `px-2 inline-flex text-xs leading-5 font-semibold rounded-full 
                            ${activity.status === 'Ativo'
                                                                    ? 'bg-green-100 text-green-800'
                                                                    : activity.status === 'Em revisão'
                                                                        ? 'bg-yellow-100 text-yellow-800'
                                                                        : 'bg-blue-100 text-blue-800'}`, children: activity.status }) })] }, activity.id))) })] }) }) }) }) })] }), _jsxs("div", { className: "mt-8", children: [_jsx("h3", { className: "text-lg leading-6 font-medium text-gray-900", children: "A\u00E7\u00F5es R\u00E1pidas" }), _jsxs("div", { className: "mt-4 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3", children: [_jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsxs("div", { className: "px-4 py-5 sm:p-6", children: [_jsx("h4", { className: "text-lg font-medium text-gray-900", children: "Adicionar Institui\u00E7\u00E3o" }), _jsx("p", { className: "mt-1 text-sm text-gray-500", children: "Cadastre uma nova institui\u00E7\u00E3o parceira na plataforma." }), _jsx("button", { type: "button", className: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", children: "Adicionar" })] }) }), _jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsxs("div", { className: "px-4 py-5 sm:p-6", children: [_jsx("h4", { className: "text-lg font-medium text-gray-900", children: "Cadastrar Curso" }), _jsx("p", { className: "mt-1 text-sm text-gray-500", children: "Registre um novo curso para certifica\u00E7\u00E3o." }), _jsx("button", { type: "button", className: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", children: "Cadastrar" })] }) }), _jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsxs("div", { className: "px-4 py-5 sm:p-6", children: [_jsx("h4", { className: "text-lg font-medium text-gray-900", children: "Relat\u00F3rios" }), _jsx("p", { className: "mt-1 text-sm text-gray-500", children: "Gere relat\u00F3rios financeiros e de certifica\u00E7\u00E3o." }), _jsx("button", { type: "button", className: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", children: "Gerar" })] }) })] })] })] }));
};
export default Dashboard;
